server:
  port: 8001
  
spring:
  cloud:
    consul:
      discovery:
        instanceId: ServiceA
        health-check-interval: 5s
      config:
        management: 
          enabled: true
    stream:
      bindings:
        output:
          binder: kafka
          destination: cloudEX
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  security: 
    enabled: false
